const SAVE_INPUT = 'LOGIN/SAVE_INPUT'
const EMPTY_INPUT = 'LOGIN/EMPTY_INPUT'
const AUTHORIZATION = 'LOGIN/AUTHORIZATION'
const SUCCESS_AUTHORIZATION = 'LOGIN/SUCCESS_AUTHORIZATION'
const FAILED_AUTHORIZATION = 'LOGIN/FAILED_AUTHORIZATION'
const ADD_TODO = 'TODO/ADD_TODO'
const CHANGE_COMPLETE = 'TODO/CHANGE_COMPLETE'
const CHANGE_TEXT = 'TODO/CHANGE_TEXT'
const REMOVE_TODO = 'TODO/REMOVE_TODO'
const FILTER_TODO = 'TODO/FILTER_TODO'
const GET_TODOS = 'TODO/GET_TODOS'

export {SAVE_INPUT, EMPTY_INPUT, AUTHORIZATION, SUCCESS_AUTHORIZATION, FAILED_AUTHORIZATION, ADD_TODO, CHANGE_COMPLETE, CHANGE_TEXT, REMOVE_TODO, FILTER_TODO, GET_TODOS}